basePath: /api/v1
definitions:
  internal_services_notes.NoteRequest:
    properties:
      content:
        type: string
      title:
        type: string
    required:
    - content
    - title
    type: object
  internal_services_notes.NoteUpdateRequest:
    properties:
      content:
        type: string
      id:
        type: string
      title:
        type: string
    required:
    - content
    - id
    - title
    type: object
  setUp_internal_utils.BaseResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  setUp_internal_utils.PaginationMeta:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  setUp_internal_utils.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  setUp_internal_utils.SuccessWithPaginationResponse:
    properties:
      data: {}
      message:
        type: string
      pagination:
        $ref: '#/definitions/setUp_internal_utils.PaginationMeta'
      success:
        type: boolean
    type: object
  setUp_internal_utils.ValidationErrorResponse:
    properties:
      details: {}
      error:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample server.
  title: My API
  version: "1.0"
paths:
  /notes:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all Notes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setUp_internal_utils.SuccessWithPaginationResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/setUp_internal_utils.BaseResponse'
      security:
      - BearerAuth: []
      summary: Get list of Notes
      tags:
      - Notes
    post:
      consumes:
      - application/json
      description: Add a new notes to the system
      parameters:
      - description: notes data
        in: body
        name: notes
        required: true
        schema:
          $ref: '#/definitions/internal_services_notes.NoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setUp_internal_utils.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/setUp_internal_utils.ValidationErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/setUp_internal_utils.BaseResponse'
      security:
      - BearerAuth: []
      summary: Create a new notes
      tags:
      - Notes
    put:
      consumes:
      - application/json
      description: Add a new notes to the system
      parameters:
      - description: notes data
        in: body
        name: notes
        required: true
        schema:
          $ref: '#/definitions/internal_services_notes.NoteUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setUp_internal_utils.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/setUp_internal_utils.ValidationErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/setUp_internal_utils.BaseResponse'
      security:
      - BearerAuth: []
      summary: update a new notes
      tags:
      - Notes
  /notes/{id}:
    delete:
      consumes:
      - application/json
      description: delete a new notes to the system
      parameters:
      - description: ID catatan yang akan dihapus
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setUp_internal_utils.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/setUp_internal_utils.BaseResponse'
      security:
      - BearerAuth: []
      summary: delete a new notes
      tags:
      - Notes
    get:
      consumes:
      - application/json
      description: Retrieve a Notes
      parameters:
      - description: ID catatan yang ingin dicari
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setUp_internal_utils.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/setUp_internal_utils.BaseResponse'
      security:
      - BearerAuth: []
      summary: Get a Notes
      tags:
      - Notes
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
